### PR TITLE
go.mod,docker: update dependencies

### PR DESCRIPTION
**Pull request by joshuasing**
**Summary**
Update project dependencies to latest versions.
*This includes a security update for go-ethereum, which I do not believe directly affects this project.*

### Docker images

| Dependency        | Previous          | New                 |
|-------------------|-------------------|---------------------|
| `golang` (alpine) | `1.22.2-alpine`   | `1.22.6-alpine3.20` |
| `golang` (debian) | `1.22.2-bookworm` | `1.22.6-bookworm`   |
| `postgres`        | `16`              | `16.3-alpine3.20`   |

#### Direct

| Dependency                                    | Previous               | New                    | Type  |
|-----------------------------------------------|------------------------|------------------------|-------|
| `toolchain`                                   | `go1.22.2`             | `go1.22.6`             | Patch |
| `github.com/btcsuite/btcd`                    | `v0.24.0`              | `v0.24.2`              | Patch |
| `github.com/btcsuite/btcd/btcec/v2`           | `v2.3.2`               | `v2.3.4`               | Patch |
| `github.com/coder/websocket` | `v1.8.11` | `v1.8.12` | See [notes](#notes) |
| `github.com/decred/dcrd/dcrec/secp256k1/v4`   | `v4.2.0`               | `v4.3.0`               | Patch |
| `github.com/docker/docker`                    | `v25.0.5+incompatible` | `v27.1.1+incompatible` | Major |
| `github.com/ethereum/go-ethereum`             | `v1.13.5`              | `v1.14.8`              | Minor |
| `github.com/go-test/deep`                     | `v1.1.0`               | `v1.1.1`               | Patch |
| `github.com/prometheus/client_golang`         | `v1.18.0`              | `v1.19.1`              | Minor |
| `github.com/sethvargo/go-retry`               | `v0.2.4`               | `v0.3.0`               | Minor |
| `github.com/testcontainers/testcontainers-go` | `v0.28.0`              | `v0.32.0`              | Minor |
| `golang.org/x/sys`                            | `v0.17.0`              | `v0.23.0`              | Minor |

#### Indirect

| Dependency                                                      | Previous                                | New       | Type    |
|-----------------------------------------------------------------|-----------------------------------------|-----------|---------|
| `github.com/Microsoft/go-winio`                                 | `v0.6.1`                                | `v0.6.2`  | Patch   |
| `github.com/Microsoft/hcsshim`                                  | `v0.11.4`                               | `v0.11.5` | Patch   |
| `github.com/cespare/xxhash/v2`                                  | `v2.2.0`                                | `v2.3.0`  | Minor   |
| `github.com/containerd/containerd`                              | `v1.7.13`                               | `v1.7.18` | Patch   |
| `github.com/containerd/errdefs`                                 | N/A                                     | `v0.1.0`  | New     |
| `github.com/distribution/reference`                             | `v0.5.0`                                | `v0.6.0`  | Minor   |
| `github.com/golang/protobuf`                                    | `v1.5.3`                                | `v1.5.4`  | Patch   |
| `github.com/holiman/uint256`                                    | `v1.2.3`                                | `v1.3.1`  | Minor   |
| `github.com/moby/docker-image-spec`                             | N/A                                     | `v1.3.1`  | New     |
| `github.com/pmezard/go-difflib`                                 | N/A                                     | `v1.0.0`  | New     |
| `github.com/prometheus/common`                                  | `v0.47.0`                               | `v0.48.0` | Minor   |
| `github.com/stretchr/objx`                                      | N/A                                     | `v0.5.2`  | New     |
| `github.com/stretchr/testify`                                   | N/A                                     | `v1.9.0`  | New     |
| `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` | `v0.48.0`                               | `v0.49.0` | Minor   |
| `go.opentelemetry.io/otel`                                      | `v1.23.1`                               | `v1.24.0` | Minor   |
| `go.opentelemetry.io/otel/metric`                               | `v1.23.1`                               | `v1.24.0` | Minor   |
| `go.opentelemetry.io/otel/trace`                                | `v1.23.1`                               | `v1.24.0` | Minor   |
| `golang.org/x/crypto`                                           | `v0.19.0`                               | `v0.22.0` | Minor   |
| `golang.org/x/exp`                                              | `v0.0.0-20240213143201-ec583247a57a`    | N/A       | Removed |
| `golang.org/x/mod`                                              | `v0.15.0`                               | N/A       | Removed |
| `golang.org/x/tools`                                            | `v0.18.1-0.20240311201521-78fbdeb61842` | N/A       | Removed |
| `google.golang.org/protobuf` | `v1.33.0` | `v1.34.2` | Minor |
| `gopkg.in/yaml.v3`                                              | N/A                                     | `v3.0.1`  | New     |

### Notes
`nhooyr.io/websocket` is now `github.com/coder/websocket` and is being maintained by Coder: https://coder.com/blog/websocket
Our fork has been updated to v1.8.12, which changes the package to `github.com/coder/websocket`.

### CODE REVIEW

**Comment by joshuasing** [comment]
Reverted `github.com/btcsuite/btcd/btcec/v2 v2.3.4` to `github.com/btcsuite/btcd/btcec/v2 v2.3.3` because they broke their API (in a patch...): https://github.com/btcsuite/btcd/pull/2211

We can likely bump this again once we can update `github.com/ethereum/go-ethereum/crypto` to a version that includes this fix: https://github.com/ethereum/go-ethereum/pull/30181 (https://github.com/ethereum/go-ethereum/issues/30188)

**Comment by iCapt** [comment]
Add a header and block cache.

**Comment by iCapt** [comment]
Add a header and block cache.

**Comment by iCapt** [comment]
Add a header and block cache. This branch has conflicts that must be resolved

**Review by marcopeereboom — APPROVED** [review]

**Pull request merged**
